---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mi-flota-repo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/odlymedina1983-dev/Repo_mi-flota-devops.git
