apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-limits
  namespace: dev
spec:
  hard:
    pods: "6"
    requests.cpu: "1500m"
    requests.memory: "1500Mi"
    limits.cpu: "3"
    limits.memory: "3Gi"
