apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-entrada
  # ⚠️ Se eliminó la línea "namespace: dev" para evitar el hardcodeo.
  # De este modo, Kustomize inyectará el namespace dinámicamente en DEV, QA y PROD.
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx 
  rules:
  - host: mi-flota.local
    http:
      paths:
      
      # 🚀 1. EL FRONTEND DE PODINFO (Apuntando al servicio activo de tu app unificada)
      - path: /app/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: podinfo-app
            port:
              number: 9898

      # 🔌 2. SOCKET.IO TRAFFIC (Captura y reescribe las llamadas dirigidas al puerto 3001)
      # El grupo (.*) captura todo lo que viene después de socket.io/ (como ?EIO=4&transport=websocket)
      # y lo inyecta limpiamente en el endpoint del servidor uWebSockets.
      - path: /chat/(socket.io/?.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: chat-app-svc
            port:
              number: 3001

      # 💬 3. EL BACKEND DEL CHAT (Express clásico para renderizado e HTTP estándar)
      - path: /chat/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: chat-app-svc
            port:
              number: 3000

      # 🌐 4. LANDING TRADICIONAL
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: nginx-servicio
            port:
              number: 80