apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-entrada
  # ⚠️ Quitamos el hardcodeo de namespace: dev para que el Kustomize de cada entorno lo asigne dinámicamente
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx 
  rules:
  - host: mi-flota.local
    http:
      paths:
      
      # 🚀 1. EL FRONTEND DE PODINFO
      - path: /app/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: podinfo-app
            port:
              number: 9898

      # 🔌 2. EL MOTOR DE WEBSOCKETS (uWebSockets.js + Socket.IO)
      - path: /chat/socket.io/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: chat-app-svc
            port:
              number: 3001 # 👈 Enviamos el apretón de manos directo al puerto correcto

      # 💬 3. EL BACKEND DEL CHAT (Express Clásico API/HTML)
      - path: /chat/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: chat-app-svc
            port:
              number: 3000

      # 🌐 4. LANDING TRADICIONAL
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: nginx-servicio
            port:
              number: 80