apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-app
  namespace: dev
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: "6.5.x"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    # 🚀 CONFIGURACIÓN DE TU NUEVA IMAGEN LOCAL
    image:
      repository: podinfo
      tag: v1.0.0-chat          # 👈 CAMBIA ESTO (Tu nuevo tag)
      pullPolicy: IfNotPresent  # Mantiene la orden para que busque en el K3d local

    replicaCount: 1
    ui:
      color: "#1a5276"
      message: "Mi propio Fork de Podinfo - Entorno Local"
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    
    # 🔗 EL ENLACE DE LA ALIANZA
    backend: "http://chat-app-svc:3000" # 👈 Esto está PERFECTO. Apesta al DNS interno del clúster de Rohan.
    