apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo-app.yaml     # Pon aquí el nombre exacto del archivo de podinfo que esté suelto
  - chat-engine/app.yaml # ◄── AQUÍ OBLIGAMOS A FLUX A ENTRAR A LA CARPETA