apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # 1. Namespaces (Los tres que se ven en tu árbol)
  - namespaces/cuotas-entornos.yaml
  - namespaces/entornos-namespaces.yaml
  - namespaces/infra-core-namespace.yaml

  # 2. Core (Los archivos sueltos que se ven en tu árbol)
  - core/dev-quota.yaml
  - core/ingress-nginx-controller.yaml
  - core/nginx-deployment.yaml
  - core/nginx-ingress.yaml
  - core/nginx-service.yaml

  # 3. El Chat Engine (Nuestro objetivo prioritario)
  - chat-engine/app.yaml
  - chat-engine/mongo.yaml
  - chat-engine/redis.yaml

  # 4. Gitea
  - gitea/gitea-deployment.yaml
  - gitea/gitea-network.yaml
  - gitea/gitea-pvc.yaml

  # 5. Podinfo Release (El que está en la raíz de cluster-infra)
  - podinfo-helm-release.yaml