apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-app
  namespace: dev
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: "6.5.x"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    # 🚀 CONFIGURACIÓN DE TU FORK LOCAL
    image:
      repository: podinfo
      tag: omedina-custom
      pullPolicy: IfNotPresent  # 👈 Crucial para que K3d use tu imagen importada
    replicaCount: 1
    ui:
      color: "#1a5276"          # Un azul oscuro elegante para notar el cambio de versión
      message: "Mi propio Fork de Podinfo - Entorno Local"
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"
    backend: "http://chat-app-svc:3000"
    