apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-app
  namespace: dev
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: "6.5.x"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    replicaCount: 1
    ui:
      color: "#34577c"
      message: "Laboratorio GitOps - Podinfo Front"
    # 🚀 AQUÍ ESTÁ LA LLAVE QUE DESTRABA EL LIMITRANGE:
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"