apiVersion: v1
kind: Namespace
metadata:
  name: qa
  labels:
    env: qa
    security: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    env: prod
    security: isolated
